### ISSUE TITLE
Implement basic styles

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-tiptap-rich-text-widgets#2]
Please style. See the README to get started:

https://github.com/apostrophecms/apostrophe-tiptap-rich-text-widgets

I am thinking you'll just push a `user.less` asset for 2.x.

You can't style the link modal yet because I haven't addressed the issue of modals quite yet. I'll get that roughed in and let you know.

**Comment by boutell** [comment]
You can style the link modal now although its active state for the button isn't working yet. I think we discussed changes to its UX. Maybe even separate link and anchor controls?

**Comment by boutell** [comment]
Link button active state works now.

**Comment by stuartromanek** [comment]
see #6

**Comment by boutell** [comment]
Keeping open until I have table controls working fully so we can evaluate the state of the buttons that reveals etc.
